name: Azure Streamlit Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Install Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3) Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4) Make sure your startup script is executable
      - name: Make startup.sh executable
        run: chmod +x startup.sh

      # 5) Zip the entire project (excluding venv and git metadata)
      - name: Zip the project
        run: zip -r app.zip . -x "venv/*" ".git/*"

      # 6) Deploy to Azure using the publish profile
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: Intelligent-agent       # your Azure Web App name
          package: app.zip
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
